---
name: Verify and Bump
on:
  push:
    branches:
      - main
jobs:
  checkov:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: example/examplea
          skip_check: CKV_GCP_23
          quiet: false
          framework: terraform 
          #args
          #check', 
          external_checks_dirs: checkov
          #external_checks_repos

  Bridgecrew:

    runs-on: ubuntu-latest

    steps:   
      - name: Run Bridgecrew 
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master
        with:
         api-key: ${{ secrets.BRIDGECREW_API_KEY }}
         directory: example/examplea
         skip_check: CKV_GCP_23
         #output_format: cli
         quiet: false
         external_checks_dir: checkov
         soft_fail: false

  version:
    name: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: "true"
    needs: [checkov, Bridgecrew]
