---
name: pull_request
on: pull_request
jobs:
  checkov:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: example/examplea
          skip_check: CKV_GCP_23
          quiet: false
          framework: terraform 
          #args
          #check', 
          external_checks_dirs: checkov
          #external_checks_repos

  Bridgecrew:

    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Run Bridgecrew 
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master
        with:
         api-key: ${{ secrets.BRIDGECREW_API_KEY }}
         directory: example/examplea
         skip_check: CKV_GCP_23
         output_format: cli
         quiet: false
         #external_checks_dir: checkov
         soft_fail: false

